---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php packages
    tags: apache, apache2, php
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
  
  - name: change email address for admin
    tags: apache
    lineinfile:
      path: /etc/apache2/sites-available/000-default.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin jeffry@gmail.com
    when: ansible_distribution == "Ubuntu"
    register: apache2

  - name: restart apache2
    tags: apache2
    service:
      name: apache2
      state: restarted
    when: apache2.changed



  - name: copy defaul html file for site
    tags: apache, apache2
    copy: 
      src: ../files/default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
  
  - name: Disable apache2 service
    tags: apache, ubuntu
    service:
      name: apache2
      state: started
    when: ansible_distribution == "Ubuntu"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Ubuntu)
    tags: mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest

- hosts: all
  become: true
  tasks:

    - name: create jeff user
      tags: always
      user:
        name: jeff
        groups: root

    - name: add shh key
      tags: always
      authorized_key:
        user: jeff
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO7oHOx1D7mNwySNKYg+Lvrqf35qJK6bS3pe9q6IJybt ansible"

    - name: add sudoers file for jeff
      copy:
        src: sudoer_jeff
        dest: /etc/sudoers.d/jeff
        owner: root
        group: root
        mode: 0440

- hosts: workstations
  become: true
  tasks:

    - name: install unzip
      package:
        name: unzip

    - name: install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.4.2/terraform_1.4.2_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root
